; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CF862B5E-960E-43E2-8604-8CD53036A186}
AppName=RSciTE ContextMenu
AppVerName=RSciTE ContextMenu 1.0
AppPublisher=Roberto Rossi
AppPublisherURL=http://www.redchar.net/
AppSupportURL=http://www.redchar.net/
AppUpdatesURL=http://www.redchar.net/
CreateAppDir=no
OutputBaseFilename=regContextMenu
Compression=lzma
SolidCompression=yes
Uninstallable=no
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
;Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin

  if (CurStep=ssPostInstall) then
  begin //post installazione
  
    if IsWin64 then
    begin
      //registrazione menu contestuale a 64 bit
      if FileExists(ExpandConstant('{src}\wscitecm64_en.dll')) then
      begin
        Exec('regsvr32.exe', ExpandConstant('"{src}\wscitecm64_en.dll"'), '', SW_SHOW,
              ewWaitUntilTerminated, ResultCode)
      end;
      if FileExists(ExpandConstant('{src}\wscitecm64_it.dll')) then
      begin
        Exec('regsvr32.exe', ExpandConstant('"{src}\wscitecm64_it.dll"'), '', SW_SHOW,
              ewWaitUntilTerminated, ResultCode)
      end;
    end;

    //registrazione menu contestuale a 64 bit
    if FileExists(ExpandConstant('{src}\wscitecm_en.dll')) then
    begin
        Exec('regsvr32.exe', ExpandConstant('"{src}\wscitecm_en.dll"'), '', SW_SHOW,
              ewWaitUntilTerminated, ResultCode)
    end;
    if FileExists(ExpandConstant('{src}\wscitecm_it.dll')) then
    begin
        Exec('regsvr32.exe', ExpandConstant('"{src}\wscitecm_it.dll"'), '', SW_SHOW,
              ewWaitUntilTerminated, ResultCode)
    end;

  end; //endpostinstall

end; //endCurStepChanged



